### ISSUE TITLE
Final(?) PHP Notice question

### ISSUE THREAD

**Issue by silsbyc** [rrennick/shardb#3]
I think this is the last PHP Notice that I'll submit. 

PHP Notice:  Undefined index: global_r in /wp-content/db.php on line 430

The same notice is appearing on font and back end, on the main site and on subfolder sites.

This doesn't seem to be breaking anything, but I just want to be sure it isn't going to come back in a couple months after our upgrade to mess up something in the sharded database.

Thank you again for the quick fixes on these Notices!

**Comment by rrennick** [comment]
Fixed in https://github.com/rrennick/shardb/compare/develop. 

Thanks again for reporting :)

**Comment by silsbyc** [comment]
Still getting the same Notice.

Does it matter that the Notice is returning "global_r" without the $shardb_prefix that has been set in db-settings.php?

**Comment by rrennick** [comment]
global_r is index key for read global database. If it was global_w then it would be write.

Same line #?

**Comment by silsbyc** [comment]
Yes, same line: 430.

**Comment by rrennick** [comment]
Sorry, I was sick this week so I didn't get to this. I fixed the second warning on that same line.
