### ISSUE TITLE
Another PHP Notice and Breaking Pagination?

### ISSUE THREAD

**Issue by silsbyc** [rrennick/shardb#4]
Not sure why this is breaking pagination, but confirmed that returning to the pre-php7 version restores pagination to the admin All Posts view.

The error that appears in the debug log when viewing All Posts from the admin dashboard of a site on the network is: 
PHP Notice:  Undefined index: xxx_r in /wp-content/db.php on line 441
PHP Notice:  Undefined index: xxx_r in /wp-content/db.php on line 484

(where xxx is the shardb dataset and number)

**Comment by rrennick** [comment]
Should be fixed in https://github.com/rrennick/shardb/tree/develop

**Comment by silsbyc** [comment]
Undefined variable: k in /wp-content/db.php on line 485

**Comment by silsbyc** [comment]
I also deactivated all other plugins and all themes, but pagination still does not return to the Admin tables with this php7-compatible version of shardb active.

**Comment by rrennick** [comment]
Can you clarify how pagination is not working?

**Comment by silsbyc** [comment]
When running the php7-compatible version of shardb (even on php5): 
On the admin side, if I go to a site that has more posts than will appear in one All Posts table, the pagination links do not appear. I can still type ?paged=2 to the end of the address (ie, /wp-admin/edit.php?paged=2) to make the pagination links appear. 

On the front end, the links for paging on Recent Posts do not appear. 

If I revert to the php5 version of shardb, the pagination links reappear.

**Comment by rrennick** [comment]
Updated develop branch to fix retaining `found_rows()`.

**Comment by silsbyc** [comment]
Paging is back in business. You rock!

**Comment by rrennick** [comment]
AWesome, thanks :)
